/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as WhyAntofityRouteImport } from './routes/why-antofity'
import { Route as AdminCatalogueRouteImport } from './routes/admin/catalogue'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as CatalogueIndexRouteImport } from './routes/catalogue/index'
import { Route as CatalogueItemIdRouteImport } from './routes/catalogue/$itemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyAntofityRoute = WhyAntofityRouteImport.update({
  id: '/why-antofity',
  path: '/why-antofity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogueRoute = AdminCatalogueRouteImport.update({
  id: '/admin/catalogue',
  path: '/admin/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueIndexRoute = CatalogueIndexRouteImport.update({
  id: '/catalogue/',
  path: '/catalogue/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueItemIdRoute = CatalogueItemIdRouteImport.update({
  id: '/catalogue/$itemId',
  path: '/catalogue/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/solutions': typeof SolutionsRoute
  '/why-antofity': typeof WhyAntofityRoute
  '/admin/catalogue': typeof AdminCatalogueRoute
  '/admin/login': typeof AdminLoginRoute
  '/catalogue/$itemId': typeof CatalogueItemIdRoute
  '/catalogue/': typeof CatalogueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/solutions': typeof SolutionsRoute
  '/why-antofity': typeof WhyAntofityRoute
  '/admin/catalogue': typeof AdminCatalogueRoute
  '/admin/login': typeof AdminLoginRoute
  '/catalogue/$itemId': typeof CatalogueItemIdRoute
  '/catalogue': typeof CatalogueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/solutions': typeof SolutionsRoute
  '/why-antofity': typeof WhyAntofityRoute
  '/admin/catalogue': typeof AdminCatalogueRoute
  '/admin/login': typeof AdminLoginRoute
  '/catalogue/$itemId': typeof CatalogueItemIdRoute
  '/catalogue/': typeof CatalogueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/industries'
    | '/solutions'
    | '/why-antofity'
    | '/admin/catalogue'
    | '/admin/login'
    | '/catalogue/$itemId'
    | '/catalogue/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/industries'
    | '/solutions'
    | '/why-antofity'
    | '/admin/catalogue'
    | '/admin/login'
    | '/catalogue/$itemId'
    | '/catalogue'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/industries'
    | '/solutions'
    | '/why-antofity'
    | '/admin/catalogue'
    | '/admin/login'
    | '/catalogue/$itemId'
    | '/catalogue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  SolutionsRoute: typeof SolutionsRoute
  WhyAntofityRoute: typeof WhyAntofityRoute
  AdminCatalogueRoute: typeof AdminCatalogueRoute
  AdminLoginRoute: typeof AdminLoginRoute
  CatalogueItemIdRoute: typeof CatalogueItemIdRoute
  CatalogueIndexRoute: typeof CatalogueIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-antofity': {
      id: '/why-antofity'
      path: '/why-antofity'
      fullPath: '/why-antofity'
      preLoaderRoute: typeof WhyAntofityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalogue': {
      id: '/admin/catalogue'
      path: '/admin/catalogue'
      fullPath: '/admin/catalogue'
      preLoaderRoute: typeof AdminCatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue/': {
      id: '/catalogue/'
      path: '/catalogue'
      fullPath: '/catalogue/'
      preLoaderRoute: typeof CatalogueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue/$itemId': {
      id: '/catalogue/$itemId'
      path: '/catalogue/$itemId'
      fullPath: '/catalogue/$itemId'
      preLoaderRoute: typeof CatalogueItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  SolutionsRoute: SolutionsRoute,
  WhyAntofityRoute: WhyAntofityRoute,
  AdminCatalogueRoute: AdminCatalogueRoute,
  AdminLoginRoute: AdminLoginRoute,
  CatalogueItemIdRoute: CatalogueItemIdRoute,
  CatalogueIndexRoute: CatalogueIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
